import React from 'react';
    import { Link } from 'react-router-dom';
    import './LandingPage.css';

    function LandingPage() {
      return (
        <div className="landing-container">
          <section className="hero">
            <h1>Prepare for CSS Exam 2026 with AI-Powered Tools</h1>
            <p>Get access to AI-generated notes, exam checking, and more.</p>
            <div className="cta-buttons">
              <Link to="/signup" className="cta-button signup">Sign Up</Link>
              <Link to="/login" className="cta-button login">Login</Link>
            </div>
          </section>

          <section className="features">
            <h2>Key Features</h2>
            <div className="feature-grid">
              <div className="feature-item">
                <h3>AI-Generated Notes</h3>
                <p>Access comprehensive notes generated by AI to aid your preparation.</p>
              </div>
              <div className="feature-item">
                <h3>Exam Checker System</h3>
                <p>Upload your answer sheets and get AI-based performance evaluation.</p>
              </div>
              <div className="feature-item">
                <h3>Pricing Tiers</h3>
                <p>Choose a plan that fits your needs.</p>
              </div>
            </div>
          </section>
        </div>
      );
    }

    export default LandingPage;
